#!/bin/sh

# Copyright (c) 2015 Frank Terbeck <ft@bewatermyfriend.org>
# All rights reserved.
#
# Terms for redistribution and use can be found in LICENCE.

exec sh lib/run-scheme.sh "$PWD/lib/import-time-sheet.scm"
