#!/bin/sh

GUILE_LOAD_PATH=$PWD/scheme
export GUILE_LOAD_PATH

for dir in scheme/*/*/*/*/*/ scheme/*/*/*/*/ \
           scheme/*/*/*/ scheme/*/*/ scheme/*/ scheme/; do
    [ ! -d "$dir" ] && continue
    printf 'Entering directory `%s'\''...\n' "$dir"
    (cd "$dir" && for input in *.scm; do
                      [ ! -f "$input" ] && continue
                      output="${input%.*}.go"
                      [ -e "$output" ] && [ "$output" -nt "$input" ] && continue
                      guild compile -Wunsupported-warning \
                                    -Wunused-variable \
                                    -Wunused-toplevel \
                                    -Wunbound-variable \
                                    -Warity-mismatch \
                                    -Wduplicate-case-datum \
                                    -Wbad-case-datum \
                                    -Wformat \
                                    -o "$output" "$input" || exit 1
                  done; ) || exit 1
done

